### ISSUE TITLE
How to add config for RealFuels?

### ISSUE THREAD

**Issue by dertroglodyt** [marce155/KSP-BAM#1]
I extracted the resource names from real fuels and made some (crude) values up.
What's the right way to add them? Paste them in bam.cfg or add another bam_realfuels.cfg? Will both configs be "combined" somehow?

Just in case you want to add them:
resdef = LqdOxygen,0.001;Kerosene,0.001;LqdHydrogen,0.0025;NTO,0.001;UDMH,0.001;Aerozine50,0.001;MMH,0.001;HTP,0.001;AvGas,0.001;IRFNA-III,0.001;NitrousOxide,0.0015;Aniline,0.001;Ethanol75,0.001;LqdAmmonia,0.001;LqdMethane,0.001;ClF3,0.001;ClF5,0.001;Diborane,0.001;Pentaborane,0.001;Ethane,0.001;Ethylene,0.002;OF2,0.002;LqdFluorine,0.003;N2F4,0.002;Methanol,0.001;Furfuryl,0.001;UH25,0.001;Tonka250,0.001;Tonka500,0.001;FLOX30,0.001;FLOX70,0.001;FLOX88,0.001;IWFNA,0.001;IRFNA-IV,0.001;AK20,0.001;AK27,0.001;MON1,0.001;MON3,0.001;MON10,0.001;MON15,0.001;MON20,0.001;Hydyne,0.001;Syntin,0.001;LeadBallast,-0.001

**Comment by marce155** [comment]
Just replace the line in the one BAM.cfg
I know it's not a perfect solution, but working with multiple configs is really annoying in KSP ;)

I'll post them in the thread for people who need it!
